create table ADMIN.USERS
(
    id         number
        generated always
            as identity (start with 1000000 increment by 1)
        primary key,
    username   varchar(32 char) unique not null, -- add char!!!!
    password   varchar2(64 char)       not null,
    email      varchar2(64 char)       not null unique,
    role       varchar2(10 char) check (role in ('user', 'landlord', 'admin')),
    cell_phone varchar(15 char)
) tablespace TS_RENT;

create table ADMIN.RECORD_TYPES
(
    id          number
        generated by default
            as identity (start with 1000 increment by 1)
        primary key,
    name        varchar2(128 char) unique,
    description varchar2(512 char) null,
    sub_type_of int
                              null
        references ADMIN.RECORD_TYPES (id)
) tablespace TS_RENT;

drop table ADMIN.RECORD_TYPES purge;
drop table ADMIN.USERS purge;
